/**
 * Regenerates committed geo assets for static `v1` and validation helpers.
 *
 * Usage (repo root): `npm run generate:geo`
 */
import { mkdir, writeFile } from "node:fs/promises";
import { resolve } from "node:path";
import { buildE164CallingCodeSeedValues } from "../src/lib/geo/telephony-seed-values";
import { mergePacks } from "../src/lib/ingestion/ingest-seed-bundle";
import { buildGeoPacks } from "./sources/geo-build";

type GeoBundle = {
  version: 1;
  generated_at: string;
  countries: Array<{ key: string; label: string; aliases?: string[]; metadata?: Record<string, unknown> }>;
  subdivisions: Array<{ key: string; label: string; aliases?: string[]; metadata?: Record<string, unknown> }>;
  region_groups: Array<{ key: string; label: string; aliases?: string[]; metadata?: Record<string, unknown> }>;
  continents: Array<{ key: string; label: string; aliases?: string[]; metadata?: Record<string, unknown> }>;
  calling_codes: Array<{ key: string; label: string; aliases?: string[]; metadata?: Record<string, unknown> }>;
};

const POSTAL_PATTERN_SOURCE: Record<string, string> = {
  NL: "^[1-9][0-9]{3}\\s?[A-Za-z]{2}$",
  CA: "^[A-Za-z]\\d[A-Za-z]\\s?\\d[A-Za-z]\\d$",
  US: "^\\d{5}(-\\d{4})?$",
  GB: "^[A-Za-z]{1,2}\\d[A-Za-z\\d]?\\s*\\d[A-Za-z]{2}$",
  DE: "^\\d{5}$",
  FR: "^\\d{5}$",
  ES: "^\\d{5}$",
  IT: "^\\d{5}$",
  PT: "^\\d{4}-\\d{3}$",
  BE: "^\\d{4}$",
  AT: "^\\d{4}$",
  CH: "^\\d{4}$",
  SE: "^\\d{3}\\s?\\d{2}$",
  NO: "^\\d{4}$",
  DK: "^\\d{4}$",
  FI: "^\\d{5}$",
  PL: "^\\d{2}-\\d{3}$",
  IE: "^[A-Za-z][0-9]{2}\\s?[A-Za-z0-9]{4}$",
  JP: "^\\d{3}-\\d{4}$",
  AU: "^\\d{4}$",
  BR: "^\\d{5}-?\\d{3}$",
  IN: "^\\d{6}$",
  CN: "^\\d{6}$",
  KR: "^\\d{5}$",
  SG: "^\\d{6}$",
  MY: "^\\d{5}$",
  TH: "^\\d{5}$",
  PH: "^\\d{4}$",
  VN: "^\\d{5}$",
  ID: "^\\d{5}$",
  NZ: "^\\d{4}$",
  ZA: "^\\d{4}$",
  AR: "^[A-Za-z][0-9]{4}[A-Za-z]{3}$",
  MX: "^\\d{5}$",
  TR: "^\\d{5}$",
  RU: "^\\d{6}$",
  IL: "^(\\d{5}|\\d{7})$",
  AE: "^\\d{5}$",
  SA: "^\\d{5}$",
};

const ADDRESS_TEMPLATES: Record<
  string,
  {
    required_fields: string[];
    field_order: string[];
    postal_code_position: string;
    region_required: boolean;
  }
> = {
  NL: {
    required_fields: ["street", "house_number", "postal_code", "city", "country"],
    field_order: ["street", "house_number", "postal_code", "city", "country"],
    postal_code_position: "before_city",
    region_required: false,
  },
  US: {
    required_fields: ["street", "city", "state", "postal_code", "country"],
    field_order: ["street", "city", "state", "postal_code", "country"],
    postal_code_position: "before_country",
    region_required: true,
  },
  CA: {
    required_fields: ["street", "city", "province", "postal_code", "country"],
    field_order: ["street", "city", "province", "postal_code", "country"],
    postal_code_position: "before_country",
    region_required: true,
  },
  DE: {
    required_fields: ["street", "postal_code", "city", "country"],
    field_order: ["street", "postal_code", "city", "country"],
    postal_code_position: "before_city",
    region_required: false,
  },
  FR: {
    required_fields: ["street", "postal_code", "city", "country"],
    field_order: ["street", "postal_code", "city", "country"],
    postal_code_position: "before_city",
    region_required: false,
  },
  GB: {
    required_fields: ["street", "city", "postal_code", "country"],
    field_order: ["street", "city", "postal_code", "country"],
    postal_code_position: "after_city",
    region_required: false,
  },
};

async function main() {
  process.env.FEELDKIT_SOURCE_FORCE_SNAPSHOTS = "1";
  const geoPacks = await buildGeoPacks();
  const merged = mergePacks(geoPacks);
  const geo = merged.get("geo");
  if (!geo) throw new Error("mergePacks: missing geo");

  const countries = geo.fieldTypes.find((ft) => ft.key === "countries")?.values ?? [];
  const subdivisions = geo.fieldTypes.find((ft) => ft.key === "subdivisions")?.values ?? [];
  const region_groups = geo.fieldTypes.find((ft) => ft.key === "geo_region_groups")?.values ?? [];
  const continents = geo.fieldTypes.find((ft) => ft.key === "geo_continents")?.values ?? [];
  const calling_codes = buildE164CallingCodeSeedValues();

  const bundle: GeoBundle = {
    version: 1,
    generated_at: new Date().toISOString(),
    countries,
    subdivisions,
    region_groups,
    continents,
    calling_codes,
  };

  const outDir = resolve(process.cwd(), "src/data/generated");
  await mkdir(outDir, { recursive: true });

  await writeFile(resolve(outDir, "geo-bundle.json"), JSON.stringify(bundle, null, 2), "utf8");

  const postalTs = `/* eslint-disable */\n/** Auto-generated by scripts/generate-geo-assets.ts — run npm run generate:geo */\nexport const POSTAL_PATTERN_SOURCE: Record<string, string> = ${JSON.stringify(POSTAL_PATTERN_SOURCE, null, 2)};\n`;
  await writeFile(resolve(outDir, "postal-patterns.ts"), postalTs, "utf8");

  const addrTs = `/* eslint-disable */\n/** Auto-generated by scripts/generate-geo-assets.ts */\nexport type AddressTemplateV1 = {\n  required_fields: string[];\n  field_order: string[];\n  postal_code_position: string;\n  region_required: boolean;\n};\n\nexport const ADDRESS_TEMPLATES_BY_ISO2: Record<string, AddressTemplateV1> = ${JSON.stringify(ADDRESS_TEMPLATES, null, 2)};\n`;
  await writeFile(resolve(outDir, "address-templates.ts"), addrTs, "utf8");

  console.log(
    `generate:geo wrote geo-bundle.json (${countries.length} countries, ${subdivisions.length} subdivisions, ${region_groups.length} region groups, ${continents.length} continents, ${calling_codes.length} calling codes), postal-patterns.ts, address-templates.ts`,
  );
}

main().catch((e) => {
  console.error(e);
  process.exit(1);
});
